apiVersion: v1
kind: Service
metadata:
  labels:
    app: arenaclient
    environment: production
  name: prod-arenaclient
  namespace: default
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8765
  selector:
    app: arenaclient
    environment: production
  sessionAffinity: None
  type: NodePort