namePrefix: prod-
commonLabels:
  environment: production
bases:
- ../../base
patches:
- image.yaml
- replica_count.yaml
configMapGenerator:
- name: config
  behavior: merge
  files:
  - configs/config.py
