apiVersion: v1
kind: Service
metadata:
  labels:
    app: arenaclient
  name: arenaclient
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8765
  selector:
    app: arenaclient
  sessionAffinity: None
  type: ClusterIP
