---
apiVersion: v1
data:
  config.py: "import os\r\nfrom urllib import parse\r\nfrom arenaclient.match.matches import HttpApiMatchSource\r\nARENA_CLIENT_ID = \"ac_name\"\r\nAPI_TOKEN = \"ac_key\"\r\nROUNDS_PER_RUN = 1\r\nBASE_WEBSITE_URL = \"api_endpoint\"\r\nAPI_MATCHES_URL = parse.urljoin(BASE_WEBSITE_URL, \"/api/arenaclient/matches/\")\r\nAPI_RESULTS_URL = parse.urljoin(BASE_WEBSITE_URL, \"/api/arenaclient/results/\")\r\nAPI_SET_STATUS_URL = parse.urljoin(BASE_WEBSITE_URL, \"/api/arenaclient/set-status/\")\r\nMATCH_SOURCE_CONFIG = HttpApiMatchSource.HttpApiMatchSourceConfig(api_url=BASE_WEBSITE_URL,api_token=API_TOKEN)\r\n# PATHS AND FILES\r\nTEMP_PATH = \"/tmp/aiarena/\"\r\nLOCAL_PATH = os.path.dirname(__file__)\r\nWORKING_DIRECTORY = LOCAL_PATH  # same for now\r\nLOG_FILE = os.path.join(WORKING_DIRECTORY, \"../logs/aiarena-client.log\")\r\nREPLAYS_DIRECTORY = os.path.join(WORKING_DIRECTORY, \"../replays\")\r\nBOTS_DIRECTORY = os.path.join(WORKING_DIRECTORY, \"../bots\")\r\nCLEAN_BOT_DIRECTORIES_BEFORE_MATCH_START = False\r\nSC2_HOME = \"/root/StarCraftII/\"\r\nMAX_GAME_TIME = 80640"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    environment: production
  name: prod-config-t87b8m2htm
